### ISSUE TITLE
Not compiling on macOS Big Sur 11.3

### ISSUE THREAD

**Issue by alxgrk** [lachrist/posix-socket#2]
Hey,

when I tried to install https://github.com/applandinc/appmap-agent-js/tree/alpha, I got the following error on Mac:
```sh
> posix-socket@1.0.1 install .../appmap-agent-js/node_modules/posix-socket-messaging/node_modules/posix-socket
> node-gyp rebuild

  CXX(target) Release/obj.target/addon/src/main.o
../src/main.cpp:292:101: error: no member named 'GetBackingStore' in 'v8::ArrayBuffer'
  ssize_t size = send(info[0]->Int32Value(context).FromMaybe(0), v8::ArrayBuffer::Cast(*(info[1]))->GetBackingStore()->Data(), info[2]->Int32Value(context).FromMaybe(0), info[3]->Int32Value(context).FromMaybe(0));
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../src/main.cpp:320:105: error: no member named 'GetBackingStore' in 'v8::ArrayBuffer'
    ssize_t size = sendto(info[0]->Int32Value(context).FromMaybe(0), v8::ArrayBuffer::Cast(*(info[1]))->GetBackingStore()->Data(), info[2]->Int32Value(context).FromMaybe(0), info[3]->Int32Value(context).FromMaybe(0), address, length);
                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../src/main.cpp:346:101: error: no member named 'GetBackingStore' in 'v8::ArrayBuffer'
  ssize_t size = recv(info[0]->Int32Value(context).FromMaybe(0), v8::ArrayBuffer::Cast(*(info[1]))->GetBackingStore()->Data(), info[2]->Int32Value(context).FromMaybe(0), info[3]->Int32Value(context).FromMaybe(0));
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../src/main.cpp:373:105: error: no member named 'GetBackingStore' in 'v8::ArrayBuffer'
  ssize_t size = recvfrom(info[0]->Int32Value(context).FromMaybe(0), v8::ArrayBuffer::Cast(*(info[1]))->GetBackingStore()->Data(), info[2]->Int32Value(context).FromMaybe(0), info[3]->Int32Value(context).FromMaybe(0), address, &actual_length);
                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
4 errors generated.
make: *** [Release/obj.target/addon/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (.../node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 20.4.0
gyp ERR! command ".../v8.11.3/bin/node" ".../v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd .../appmap-agent-js/node_modules/posix-socket-messaging/node_modules/posix-socket
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix-socket@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

As you can see, the node version 8.11.3 was used here. I also tried it with 10.13.0, 11.15.0 and 12.22.1 with the same error.

Do you have any idea how this can be fixed?
Best regards

**Comment by lachrist** [comment]
Hi Alexander, thanks for your interest. The `GetBackingStore` method is only present into v8 starting from node 14.x. The quickest fix would consists to use a compatible node version. I will also work on making this code more portable, hopefully during this week.

Best,
Laurent

**Comment by alxgrk** [comment]
Wow, thanks for the quick response! I'll try it again with 14.x and look forward to your changes concerning backward compatibility.

**Comment by lachrist** [comment]
Hi again Alexander, the last version should support node 12 as well as any currently maintained node release `((>= 12.0.0 && < 13.0.0) || >= 14.0.0)`. There is no plan at the moment to support node releases which are in end-of-life phase. cf: https://github.com/nodejs/Release

**Comment by alxgrk** [comment]
Hey Laurent, thanks nonetheless! I'll try to upgrade my application to node 12 then.

**Comment by lachrist** [comment]
I’m actually interested into how the project came into relying on legacy node version. Could you tell me a bit more about it? I could use these infos to discuss with the team whether end-of-life node release should also be supported.

Best,
Laurent

**Comment by alxgrk** [comment]
Actually, I only recently joined the team which created that project, so I can't provide more details about the reason why it still relies on that legacy version, sorry.
